name: firebase_remainder_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.3
  get: ^4.6.6
  firebase_core: ^3.8.0
  another_flushbar: ^1.12.30
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.5.0
  firebase_database: ^11.1.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^3.0.1
  rxdart: ^0.28.0
  permission_handler: ^11.3.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  flutter_gen_runner:
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/dragon.jpg
    - assets/images/dragon_pic.jpg
    - assets/images/demon.jpg
    - assets/images/fighting.jpg
    - assets/images/google_logo.png
