name: firebase_auth_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.3
  get: ^4.6.6
  firebase_core: ^3.8.0
  another_flushbar: ^1.12.30
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png
